#!/usr/bin/env sh

for i in cmd/*; do
    util=$(basename $i)
    help="$(eval $util --help 2>&1)"
echo "
## $util

\`\`\`
$help
\`\`\`

Install:

\`\`\`
go install github.com/MahouShoujoMivutilde/shellbin/cmd/$util@latest
\`\`\`
"
done
